name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v4

      - name: Get pnpm store directory
        id: pnpm-store
        run: |
          STORE_PATH=$(pnpm store path)
          echo "📦 pnpm store path: $STORE_PATH"
          echo "path=$STORE_PATH" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v5
        with:
          path: ${{ steps.pnpm-store.outputs.path }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - run: pnpm install --frozen-lockfile

      - run: pnpm typecheck

      - run: pnpm format

      - run: pnpm build
